### PR TITLE
Merge PPM

### PR DESCRIPTION
**Pull request by Naxela**
[PPM](https://github.com/Naxela/PPM) Redone and ready to be merged with Armory as mentioned in https://github.com/Naxela/PPM/issues/4#issuecomment-593567673

A brief overview of the commit:

**Post-Processing Module**

_Post-Processing Module (Formerly Post-Processing Volumes) is an addon for Armory3D that implements realtime colorgrading and implements both existing and new shaders as uniforms that can be fully controlled both through Haxe and through Logic Nodes._

PPM

The nodes are grouped under "Postprocess", and the haxe values are located in the file "Postprocess.hx located in the renderpath folder", with uniform variables passed into the following arrays:

```
colorgrading_global_uniforms
colorgrading_shadow_uniforms
colorgrading_midtone_uniforms
colorgrading_highlight_uniforms
camera_uniforms
tonemapper_uniforms
ssr_uniforms
bloom_uniforms
ssao_uniforms
lenstexture_uniforms
chromatic_aberration_uniforms
```

**Example video of the module in use:**

[PPM](https://youtu.be/ctAQag4xknY "Postprocessing Module")

PPM03A

Documentation is on my todo list for now

### CODE REVIEW

**Comment by luboslenco** [comment]
Wohoo, thanks!🎉

**Comment by Naxela** [comment]
Neat! - Perhaps in the future, [Lightmapping](https://github.com/Naxela/The_Lightmapper) can get merged in as well?

**Comment by luboslenco** [comment]
Yes, let's do it! 🙂

**Comment by Naxela** [comment]
Alrighty! - I'm a bit in doubt of what the best approach in terms of keeping the arm file structure, and without having lightmapping menues all over the place. I'm a bit afraid of messing with git and ending up ruining stuff too, maybe a different branch at first would do well for testing ([similar to the greasy pencil stuff?](https://github.com/armory3d/armory/tree/grease)), not sure if that's what branches are for.

I guess the lightmapping could go well as a dropdown-option inside the Armory bake panel, and the individual lightmapping objects available through the Armory Object Properties menu?

**Comment by luboslenco** [comment]
> I guess the lightmapping could go well as a dropdown-option inside the Armory bake panel, and the individual lightmapping objects available through the Armory Object Properties menu?

Sounds great. I have created a new branch as you suggested at https://github.com/armory3d/armory/tree/lightmapper, so no prob messing with git there.

**Pull request merged**
