### PR TITLE
Update input_on_keyboard.py

### PR DESCRIPTION
**Pull request by Sandy10000**
fix keyboard input logic node

### CODE REVIEW

**Comment by mistajuliax** [comment]
Hi, i think it's already been fixed and merged here : https://github.com/armory3d/armory/pull/1307/commits/38225873148176b102da0277c13e95adb2569b49

**Comment by Sandy10000** [comment]
Hello, Thank you for comment.
The previously modified file is [input_keyboard.py].
It is [input_on_keyboard.py] that I am asking for correction this time.
Different files with similar names.

**Comment by mistajuliax** [comment]
Ok, sorry i read too fast...

**Comment by luboslenco** [comment]
Thanks!

**Pull request merged**
