### PR TITLE
Add a "From Scene" Option to the SpawnObject Node

### PR DESCRIPTION
**Pull request by zicklag**
Allow spawning objects from other scenes with the SpawnObject node. This requires armory3d/iron#50.

### CODE REVIEW

**Comment by luboslenco** [comment]
Thanks! I am hoping we can solve this using the collections feature in b2.8, so we don't have to parse a new scene file when spawning an object. Will take a look at it asap as we migrate to b2.8 beta (hopefully that begins next week).

**Comment by zicklag** [comment]
Are we going to still support b2.79 when b2.8 comes out?

**Comment by luboslenco** [comment]
We can discuss together on forums/discord once beta is out to evaluate it. But ideally we drop b2.79 asap to develop faster. 🙂

**Comment by Bugsbane** [comment]
Any word on this now that the 0.6 beta with Blender 2.8 is out?

**Comment by jeske** [comment]
Spawning from collections is not the same feature. 

My app really needs the ability to load assets from separate files at runtim3.. as there are community developed and distributed assets.

**Comment by zicklag** [comment]
That was actually the reason that I did this, it was to support my modding integration effort. @luboslenco I think it is still valid to be able to spawn from other scenes, and this is tiny change anyway, so it shoudln't be a big deal, right?

**Comment by luboslenco** [comment]
I have been thinking about this for a long time but still fear the perf issues down the road, sorry. Nonetheless in cases where this is necessary:
- I have added a new [example](https://github.com/armory3d/armory_examples/tree/master/spawn_from_scene) showing how to manually load the scene file and then spawn single object. (use latest git armory)
- To spawn all scene objects into existing scene, [Scene.addScene()](https://github.com/armory3d/iron/blob/master/Sources/iron/Scene.hx#L296) can be used, logic nodes example [here](https://github.com/armory3d/armory_examples/blob/master/logic_examples/scenes.blend).

This should give full control over scene handling. Whenever possible, pre-reference objects in the scene.

**Pull request closed without merging**
