### PR TITLE
Removed logic nodes icons

### PR DESCRIPTION
**Pull request by knowledgenude**
I've just set all nodes icons to 'NONE' and fixed 'Set Checkbox' label name.

There are 3 commits to stay inside Github 100 files limit. I had 2 fails in the process, this is why there have "duplicated" commits.

### CODE REVIEW

**Comment by MoritzBrueckner** [comment]
Hi, I think there were some problems with Git, there are copied node files in the Armory root folder (see [this](https://github.com/armory3d/armory/tree/1fe6f7d84a79c595a8d0e9804da70172520b18b6))?

**Comment by knowledgenude** [comment]
Thanks to notice that! I tough that they only were duplicated

I should cancel these: **'Removed logic nodes icons'** and **' " (part 2)'**

Is there some place in the interface to do that? Or only trough terminal? Because i don't did it trough terminal

**Comment by MoritzBrueckner** [comment]
There is probably some way to do this directly on Github but I don't know that. If you're using a graphical Git client there should be a button "Revert commit" somewhere, otherwise use `git revert <commit hash>` in the terminal.

**Comment by knowledgenude** [comment]
I found a way to delete each file from the commit without terminal, but it took too much time. I think is faster to close this and make other PR later, but i will try to do using terminal first. Thanks for the help!

**Pull request closed without merging**
