### PR TITLE
Multi-world support

### PR DESCRIPTION
**Pull request by MoritzBrueckner**
Fixes https://github.com/armory3d/armory/issues/1734.

Requires https://github.com/armory3d/iron/pull/96.

**~This PR is WIP but opened to enable discussion, I will remove the draft status when~ it's done.**

~There is still a lot to do and the currently committed code is definitely not optimal and very messy. What makes everything more complicated is that the shader export has to be done manually for worlds as the available helper classes require materials in order to fully work. But this is out of the scope for this PR, I don't understand enough about the current system to also refactor this.~

~I currently have very limited time unfortunately, so please don't expect big updates everyday! But I will work on it :)~

---

**To do:**
- [x] Make some `Arm` world attributes individual per world
  - [x] Remove old `Arm` world attributes
- [x] Update UI
- [x] Export individual shaders per world
- [x] Replace the old world pass functionality with the new individual world shaders
  - [x] Static colors
  - [x] Hosek Wilkie skies
  - [x] Clouds
  - [x] Environment maps and static background images#
- [x] Remove world_pass
- [x] Global render path switch for clouds
- [x] Update deferred/forward render paths
- [x] Find a good solution for scene changes (Iron)
- [x] Code clean up

### CODE REVIEW

**Comment by MoritzBrueckner** [comment]
The entire world pass functionality is now reimplemented for individual words, only the Iron side of things and the render path change is missing now (at least here on Github, I already did a few things locally) :)

I decided to remove the water and fog functionality from this PR todo list as this is not related to the world shader and needs further discussion (should this be on a per-scene or per-world basis?)

**Comment by MoritzBrueckner** [comment]
I found a way to unload shaders now, the Iron commits will follow tomorrow and then it's almost ready to merge.

@luboslenco Sorry to bother you again, but in case you missed the notification: there are two open questions in the above post that we probably should resolve before merging (at least the irradiance thing). Thank you :)

**Comment by MoritzBrueckner** [comment]
I think I have found good solutions now for the questions above and this PR is ready to merge if you agree :)

**Comment by luboslenco** [comment]
Insane, thanks for pulling this off!

Regarding the make_world callback, it was a way for libraries to inject defines but I do not think it's needed anymore.

**Pull request merged**
