### PR TITLE
Fix for #2520

### PR DESCRIPTION
**Pull request by e2002e**
Translucency and volume lights fixed by Moritz and the other issue that I spotted was that the macros for the sample light require an adequate treatment at the level of the shader creation.

### CODE REVIEW

**Comment by MoritzBrueckner** [comment]
Thanks :)

Are you sure that `gbufferD` is available from the translucency shader? When I looked at this earlier today it didn't seem so to me, but maybe I'm mistaken here. `occ` however is not a uniform but defined in the shader itself, so there is no need to declare it as such.

Also, it looks like you accidentally included the changes from https://github.com/armory3d/armory/pull/2523 as well (probably doesn't matter for Git) as well as some changes relating the water pass?

**Comment by e2002e** [comment]
It's hard to debug because the alpha seems to depend on the illumination of the fragments, and despite setting it to 0.999 i have a strong transparency overall.
Capture d’écran du 2022-07-23 01-37-13

**Comment by e2002e** [comment]
No, no contact shadows on translucents.
I looked in the engine and what I see is that there are several type of shading passes : meshes and translucency are what we'r concerned with line ~90 in make_shader.py:
        elif rp == 'mesh':
            con = make_mesh.make(rp, rpasses)

        elif rp == 'shadowmap':
            con = make_depth.make(rp, rpasses, shadowmap=True)

        elif rp == 'translucent':
            con = make_transluc.make(rp)
The blend values are set to constants in make_transluc, and that might be the issue.
I tried other values with no succes yet.
When activating blending in the material, make_mesh.make deals with it and then unlit fragments appear. But the colors are pushed up. I am going to play with these blending to see if possible to get the correct transparency.
I opened an issue for that.

**Comment by e2002e** [comment]
Closing this for now as it contains also your work.

**Pull request closed without merging**
