### PR TITLE
Adding some new nodes and length() to VectorMath node

### PR DESCRIPTION
**Pull request by anadin**
@luboslenco theres a few bits in here which may not be ideal? maybe I need to split this into multiple PR's

I added Length to the VectorMath node (straight forward)

I needed a GetVelocity node which led me a little deeper into rigidbody.hx I saw a comment that it was not compiling, for me on macOS it is fine. On this node I think I should out in a extra check to make sure the rb is valid..

Also a new ApplyImpulseAtLocation node as I saw people asking for it.

Finally a VectorClampToSize node (using it to limit velocity on a rigidbody) BUT it requires updated Vec2,3 and 4 in Iron (will submit seperate PR for that)

Anyway, hope this is OK this way let me know

### CODE REVIEW

**Comment by anadin** [comment]
Actually added the Get Velocity node + added null checks and a null return when no physics

**Comment by luboslenco** [comment]
Awesome, thanks a lot!

**Comment by anadin** [comment]
No prob, thanks for fixing my formatting, will try to stick better to it - also, didn't know I could change the vector return type on the rigidbody, good to know. I had originally tried that but then switched to handling with the btvector when it didn't work :)

**Comment by luboslenco** [comment]
Sorry that was my fault on the vector return type, we can support multiple physics engines but I exposed the Bullet vector there.. now it's properly self-contained.:)

**Pull request merged**
