### PR TITLE
Update Physics Bindings for Latest Haxebullet

### PR DESCRIPTION
**Pull request by zicklag**
**Discussion:** https://github.com/armory3d/haxebullet/issues/25

### CODE REVIEW

**Comment by Amir-Arsalan** [comment]
@luboslenco Are you gonna merge this pull request soon?

**Comment by zicklag** [comment]
@Amir-Arsalan There is still one [kink](https://github.com/armory3d/haxebullet/issues/25#issuecomment-468475954) to work out before this is merged. Hopefully I will be able to get that fixed in the near future, but I've been a bit busy.

**Comment by Amir-Arsalan** [comment]
@zicklag Any updates on this?

**Comment by zicklag** [comment]
Unfortunately I have been completely out of time lately. I'll try to get it fixed as soon as I can, but I'm not positive when that will be. I haven't made any additional progress since last time.

**Comment by mistajuliax** [comment]
Hi @zicklag , i wonder if you are still evolved in armory dev as a contributor now that you develop your own engin Arsenal ? i wonder if you have time to fixed issues in bullet bindings for armory :) ? 

Regards.

**Comment by zicklag** [comment]
Hey @mistajuliax, I'll check it out again when I get the chance.

Last we left off, we were actually waiting for Haxe 4-rc3 to come out because there were bugs in both rc1 and rc2 that were blockers for the changes. Other than that, the binder that I wrote was working fine according to the tests I did.

With the new bindings, though, there were some physics issue revealed that were problems with the HashLink target that were now moved over to the Krom target because the new bindings used the same bindings for Krom as they did for HashLink. This is something that I won't be able to fix myself because I'm not well versed with the Bullet API.

---

It looks like Kha has already switched to the latest Haxe 4-preview4, so I'll test the binder with that. If the binding works, then we will just need @luboslenco review it and look into the physics issues.

**Comment by zicklag** [comment]
OK, I've updated all my PRs with the latest Armory SDK and resolved any conflicts. It appears to work fine still! :smile:

Unfortunately, Krom won't run on my system anymore because of a missing glibc 2.27. HashLink won't compile anymore either, I'm assuming for a similar reason, so I can't test Krom or HashLink.

The binder itself looks like it is working fine, and I *was* able to test successfully on the browser build, so we should be good other than the physics fixes that need to be made: see https://github.com/armory3d/haxebullet/issues/25#issuecomment-486386963.

As far as I know it should be pretty much ready, I just need review from @RobDangerous and @luboslenco.

**Comment by mistajuliax** [comment]
Hi zicklag, great news !! You are awesome ! Thanks a lot. I will try it out as soon as come back from hollidays. 

Actually i'm learning basis of coding via lua which a simple good script language to learn but it's a long way to go before co tributing myself to armory but it's the my goal and my first motivation to learn coding ! :)

Thanks a lot, Best regards.

**Comment by zicklag** [comment]
Glory to God. :slightly_smiling_face: 

If you end up trying it out, be aware that there are a set of PRs that you will have to merge to your sandbox to test it out ( see https://github.com/armory3d/haxebullet/issues/25#issuecomment-462210471 ). Tell me if you need any help with that.

**Comment by Amir-Arsalan** [comment]
@luboslenco  @RobDangerous Any updates on this?

**Comment by RobDangerous** [comment]
No, I don't even know what I would have to do with this.

**Comment by Amir-Arsalan** [comment]
@RobDangerous As far as I remember this is a major update for the physics in Armory which stabilizes the physical interactions. @zicklag Can better explain I guess :)

**Comment by RobDangerous** [comment]
I don't work on Armory. Never did.

**Comment by zicklag** [comment]
This PR is one of a [set of PRs](https://github.com/armory3d/haxebullet/issues/25#issuecomment-462210471) including ones for Kha and Khamake which are maintained by @RobDangerous.

The PR automates and unifies the physics bindings so that they are the same for HashLink and JavaScript.

While this should make it easier to stabilize and add more bindings for the physics in the fugure, these PRs only makes sure that the bindings are automated. To the contrary, because it brings the same bindings from the HashLink builds to JavaScript, the Krom target has inherited some HashLink physics bugs that need to be fixed. This is outside of the scope of the PRs and outside of my abilities to fix because I don't know a lot about actually *using* the bullet library for physics. That is something @luboslenco would have to do.

**Comment by RobDangerous** [comment]
So it's about those. Then the status is "I'm unsure whether to merge them at all".

**Comment by zicklag** [comment]
@RobDangerous Would you mind elaborating on what your concerns are? Previous [discussion](http://forum.kode.tech/topic/265/integrating-a-webidl-binder-into-khamake/9) indicated that you were open to the addition.

**Comment by RobDangerous** [comment]
I did so in that other PR. Let's continue there.

**Comment by zicklag** [comment]
Linking to https://github.com/Kode/Kha/pull/986 for reference.

**Comment by zicklag** [comment]
@luboslenco Is this still something that you are interested in merging?

**Comment by luboslenco** [comment]
Link back to https://github.com/Kode/Kha/pull/986#issuecomment-531667458.

**Comment by luboslenco** [comment]
Link to https://github.com/Kode/Kha/pull/986, hoping to revisit in the future.

**Pull request closed without merging**
