### PR TITLE
Remove haxe --times param per default

### PR DESCRIPTION
**Pull request by tong**
How about removing this flag per default ?
There isn't that much useful information in there and one could add it manually to the khafile.js if necessary.

### CODE REVIEW

**Comment by MoritzBrueckner** [comment]
What about adding it back as an option in the Armory developer settings? I guess it could be helpful to debug macro times, especially if the new assert macro should get used more.

**Comment by tong** [comment]
Sounds good too. @luboslenco opinions ?

**Comment by luboslenco** [comment]
Sounds good as an option in developer settings.

**Comment by tong** [comment]
Added.
armsdk change is here: https://github.com/armory3d/armsdk/pull/35

**Pull request merged**
