### PR TITLE
Added support for angle axies rotation nodes

### PR DESCRIPTION
**Pull request by zeeshan595**
See https://github.com/armory3d/armory/issues/1391 for details

image

### CODE REVIEW

**Comment by MoritzBrueckner** [comment]
I don't know if this works, but it could make sense (for keeping compatibility to the current `SetRotation` node) to combine both nodes (axis angle and euler) into one node which has a dropdown menu in which you can change the mode. Do you know if it is possible to change the input sockets dynamically so that they depend on the selected mode?

This would also preventing the add node menu of getting even more bloated.

Btw, I think you misspelled "Euler" in your node's title :)

**Comment by zeeshan595** [comment]
Indeed I did miss spell it which means it is miss spelled everywhere. I can have a look to see if i can merge the 2 nodes into one and fix the spelling mistake :D

**Comment by zeeshan595** [comment]
Now can use 
Euler Angles: 3d vector
Axies Angles (radians): 3d vector + float
Axies Angles (degrees): 3d vector + float
Quaternion: 3d vector + float
image

**Comment by JamieB3rt** [comment]
Oooh, this is great! Would love to have this in master. I get so many problems with rotations, i.e copying the rotation of one object to another is a nightmare! This solves so many issues i have been having!

**Comment by luboslenco** [comment]
Thanks!

**Pull request merged**
