### PR TITLE
Let's make the BxDFs more consistent! 

### PR DESCRIPTION
**Pull request by LVutner**
A small batch of BxDF fixes for Armory, to make shading a bit more consistent with Eevee render.

### CODE REVIEW

**Comment by LVutner** [comment]
More stuff coming soon

**Comment by luboslenco** [comment]
Thanks a lot!

**Comment by e2002e** [comment]
There's a typo line 265 in deferred_light.frag: envl is writen env1

**Comment by MoritzBrueckner** [comment]
Fixed in https://github.com/armory3d/armory/commit/1f6c14a0371ab0477785d4d973e2ac89fe1acd62, I don't think it needs an extra PR :)

**Pull request merged**
