### PR TITLE
Networking integration :)

### PR DESCRIPTION
**Pull request by Onek8**
computer-reaction
** hxWebSocket maintained by @ianHarrigan and other contributors is included in /Sources/armory/network with my addition of the wrapper Connect.hx file as well as a difference within one of the files regarding threads which are licensed according to the authors. My additional contribution can be CCZero cc0 public domain / MIT / ZLIB. For now I will remove the files from the library that are not used (java socket for example) and someone can change the contribution to the respective authors 
**unless the hxWebSocket is added as a submodule instead of a maintained smaller copy

### CODE REVIEW

**Comment by Armory-Community-Channel** [comment]
The networking video that will be made public when networking nodes are merged. [Video here](https://youtu.be/JyY8NvG0VtQ)

**Comment by luboslenco** [comment]
Super cool! Can you also place the hxwebsockets license alongside `/Sources/armory/network`?

**Comment by rpaladin** [comment]
License has been added and verified with the original hxWebSocket creator @ ianharrigan.

image

**Comment by Onek8** [comment]
Sorry taken from the link https://lib.haxe.org/p/hxWebSockets/

**Comment by luboslenco** [comment]
Thanks!

**Pull request merged**
