### PR TITLE
Support for Blender 3.3 LTS

### PR DESCRIPTION
**Pull request by MoritzBrueckner**
Linked to https://github.com/armory3d/armsdk/pull/48.

This is the main PR for the upcoming support for Blender 3.3 LTS versions. I will remove the draft status and post again once it's ready :)

@luboslenco It looks like Blender 3.3 is going to be released on September 7th (https://developer.blender.org/project/view/142/, I'm not sure how certain that is though), perhaps it makes sense to postpone the next SDK release to that date or to create another one on that day, but you have to decide that.

Changes (so far):
- Fixed export object visibility and some node socket indices: https://github.com/armory3d/armory/pull/2424
- Removed obsolete proxy system and replaced it with support for library overrides: https://github.com/armory3d/armory/pull/2560
- Updated socket colors and fixed incorrect drawing of socket border colors: 2ce87352a97707f85eecb81becf57251dabd4b28, 1a56a1e60b9169dbfe3b849d47aee96e35773c4f
- Changing collection properties in draw() context is no longer allowed: 04bd360cf6d8409926b7777a129ee2ad3c1b4008
- Fixed object info socket indices: c55389a8fb782b81d12e017a25ef32ed513eb515
- Replaced deprecated `Mesh.vertex_colors`: c124bc587f989eed9c34510a6dd02f9b063e8a17, ef626c5be497eb2030b9f14517657c7ef4959df8
- Updated Blender version numbers: c1510949ba278cb6aa3b4c34ae4fcc311daefb54
- Blender changed some cycles settings, most notably denoising is now active by default which massively prolonged the time taken by rendering the environment map. This was fixed in 335b89507e1443b65c0b503c4073f5e51e765c8f

This PR closes https://github.com/armory3d/armory/issues/2402.

### CODE REVIEW

**Comment by MoritzBrueckner** [comment]
I think we're ready to go :) However, depending on how the next SDK release is planned, it may not make sense to merge this yet.

@QuantumCoderQC I had to resolve a last-minute merge conflict, could you please verify that it doesn't break https://github.com/armory3d/armory/pull/2557 again?

**Comment by QuantumCoderQC** [comment]
Hi,

I confirm that #2557 works and is not broken by this PR😉

**Comment by luboslenco** [comment]
Super cool, thanks!

**Comment by tong** [comment]
Epic!

**Pull request merged**
