### PR TITLE
Fix for play button not working with Krom.

### PR DESCRIPTION
**Pull request by davidbruce**
Forces a build before compilation server to generate first krom.js.
Fixes bug where compilation server will delete krom.js if it exists during first launch.

Initial Issue:
When attempting to use the Armory Player play button with Krom the below error would occur.  To fix it you would need to disable the compilation server in the addons menu to build the Krom.js file the first time, and then you could re-enable the compilation server.    

```
__________  [Armory] Compiling  __________
Exporting Scene
Scene exported in 0.011999368667602539
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\python\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\bruce\opt\ArmorySDK//armory/blender\arm\make.py", line 33, in fn
    done()
  File "C:\Users\bruce\opt\ArmorySDK//armory/blender\arm\make.py", line 409, in compilation_server_done
    os.rename('krom/krom.js.temp', 'krom/krom.js')
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'krom/krom.js.temp' -> 'krom/krom.js'
```

I have only tested this on windows 10 and it will probably be a few days before I can get around to testing this on OSX and Linux.  If anyone else would like to give a whirl on testing it please do.

### CODE REVIEW

**Comment by e1e5en-gd** [comment]
For Armory to work correctly, you need Blender 2.83 (https://github.com/armory3d/armory/wiki/setup). I understand that you have 2.90 installed. This does not affect the current error, but you must stick to the specified version.

**Comment by davidbruce** [comment]
> 
> 
> For Armory to work correctly, you need Blender 2.83 (https://github.com/armory3d/armory/wiki/setup). I understand that you have 2.90 installed. This does not affect the current error, but you must stick to the specified version.

Thanks for the heads up.
I have tested my fix with blender 2.83LTS and it works with that version as well.

**Comment by luboslenco** [comment]
Thanks for contributing!

**Comment by e1e5en-gd** [comment]
Check, please:
https://forums.armory3d.org/t/error-trait-referenced-in-object-or-scene-not-found/4298

**Pull request merged**
